---
title: "Censored data example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{censored_data_example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(foocafeReliability)
library(rstan)
```


## Build model  Censored Data Example Ex 4.6 from Bayesian Reliabilty

See https://mc-stan.org/docs/2_21/stan-users-guide-2_21.pdf p70 for STAN
censored data documentation
```{R}

modelString <- "
  data {
    int <lower=0> Nobs;
    int <lower=0> Ncen;
    real <lower=0> yobs[Nobs];
    real <lower=0> ycen[Ncen];
  }

  parameters {
    real mu;
    real <lower=0> sigma_2;
  }

  model {
    real sigma;
    sigma = sqrt(sigma_2);
    
    target += lognormal_lpdf(yobs | mu, sigma);
    target += lognormal_lccdf(ycen | mu, sigma);

    mu ~ normal(6.5, 25);
    sigma_2 ~ inv_gamma(6.5, 23.5);
  }
  
  generated quantities {
  
    
    //sample predicted values from the model for posterior predictive checks
    real y_rep[Nobs+Ncen];
    
    real sigma;
    sigma = sqrt(sigma_2);
    
    for(n in 1:(Nobs+Ncen))
      y_rep[n] = lognormal_rng(mu, sigma);
  }
"

prowler_bearing_failures_model <- rstan::stan_model(model_code = modelString)


```

## Fit model to data
```{R}
failures <- prowler_bearing_failures$operating_hours[prowler_bearing_failures$right_censored == FALSE]
suspensions <- prowler_bearing_failures$operating_hours[prowler_bearing_failures$right_censored == TRUE]

prowler_bearing_fail_list <- list(Nobs = NROW(failures),
                            Ncen = NROW(suspensions),
                            yobs = failures,
                            ycen = suspensions
                          )

output <- rstan::sampling(prowler_bearing_failures_model, data = prowler_bearing_fail_list, chains = 4, iter = 4000, control = list(adapt_delta = 0.9))

```

```{R}

reliabilityTableList <- list()
t = seq(1,3500,100)

output_vals <- rstan::extract(output)

for (ii in 1:NROW(output_vals)){

  thisMu <- output_vals$mu[ii]
  thisSigma <- sqrt(output_vals$sigma_2[ii])
  
  get_reliability <- function(thisMu, thisSigma){
    f1 <- function(t){
      1 - pnorm((log(t) - thisMu)/thisSigma)
    }
    return(f1)
  }

  reliability <- get_reliability(thisMu, thisSigma)

  reliabilityTable <- data.frame("t" = t,
                          "reliability" = numeric(NROW(t)))

  reliabilityTable$reliability <- reliability(t)
  
  reliabilityTableList[[ii]] <- reliabilityTable
}

temp <- lapply(reliabilityTableList, '[', 2) %>% dplyr::bind_cols()

data <- data.frame(t = t,
                   meanVal = apply(temp, 1, mean),
                   LQ = apply(temp, 1, function(x) {quantile(x, 0.05)}),
                   UQ = apply(temp, 1, function(x) {quantile(x, 0.95)}))


ggplot(data = data, aes(t)) +
  geom_line(aes(y = meanVal)) +
  geom_ribbon(aes(ymin = LQ, ymax = UQ), alpha = 0.05)
  

```


# Evaluate goodness of fit
```{R}
params <- data.frame("meanlog" = rstan::extract(output)["mu"],
                     "sdlog" = rstan::extract(output)["sigma"])
colnames(params) <- c("meanlog","sdlog")

bayesian_chi_squared_test(y = prowler_bearing_failures$operating_hours,
                          distribution_fun = plnorm,
                          params = params,
                          data_type = "censored",
                          censored = prowler_bearing_failures$right_censored)

```

