---
title: "Uber censored data example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{uber_censored_data_example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rstan)
library(ggplot2)
```

# Generate data
```{R}

n = 5000
a = 2
b = 4
c = 8

data <- data.frame(x = numeric(n),
                   y = numeric(n),
                   y_obs = numeric(n),
                   observed = character(n))

data["x"] <- rnorm(n, 0, 0.34)

link <- 1/log(1+exp(a*data$x+b))

data["y"] <- rexp(n, rate = link)

data["observed"] <- data$y < c

data["y_obs"] <- data["y"]
data[data$observed == FALSE,"y_obs"] <- c

ggplot(data = data) +
  geom_point(aes(x = x, y = y, colour = "Actual"), colour = "blue") +
  geom_point(aes(x = x, y = y_obs, colour = "Observed"), colour = "turquoise") +
  geom_smooth(aes(x = x, y = y), method = lm, colour = "blue") +
  geom_smooth(data = subset(data, observed == TRUE), aes(x = x, y = y), method = lm, colour = "turquoise")

```

For info on fitting model to censored data see:

https://stackoverflow.com/questions/40289457/stan-using-target-syntax

Hamada p108 - explaination of censored data modelling


```{R}

modelString = "
  data {
    int<lower=0> Nobs;
    int <lower=0> Ncen;
    vector[Nobs] xobs;
    vector[Ncen] xcen;
    vector[Nobs] yobs;
    vector[Ncen] ycen;
  }

  parameters {
    real model_a;
    real model_b;
  }

  model {
    vector[Nobs] linkobs;
    vector[Ncen] linkcen;

    linkobs = 1 ./ log(1 + exp(model_a*xobs + model_b));
    linkcen = 1 ./ log(1 + exp(model_a*xcen + model_b));
    
    target += exponential_lpdf(yobs | linkobs);
    target += exponential_lccdf(ycen | linkcen);

    model_a ~ normal(0,10);
    model_b ~ normal(0,10);
  }
"

uber_model <- rstan::stan_model(model_code = modelString)

```

```{R}

x_obs <- data[data$observed == TRUE,"x"]
x_cen <- data[data$observed == FALSE,"x"]
y_obs <- data[data$observed == TRUE,"y_obs"]
y_cen <- data[data$observed == FALSE,"y_obs"]


stan_data_list <- list (Nobs = NROW(x_obs),
                        Ncen = NROW(x_cen),
                        xobs = x_obs,
                        xcen = x_cen,
                        yobs = y_obs,
                        ycen = y_cen
)

```


## Fit model to data
```{R}

output <- rstan::sampling(uber_model, data = stan_data_list, chains = 4, iter = 4000, control = list(adapt_delta = 0.9))

```


Plot histograms of posteriors for parameters a and b.
```{R}
stan_hist(output, c("model_a", "model_b"))
```


